services:
  # リバースプロキシ
  nginx:
    # イメージ
    image: nginx:latest

    # ポート
    ports:
      - "8443:8443"

    tty: true

    # ディレクトリ共有
    volumes:
      # 設定ファイル
      - ./nginx/configs:/etc/nginx/conf.d/

      # 静的ファイル
      - ./nginx/statics:/var/www/nginx/statics/:ro

      # SSL証明書
      - ./nginx/keys:/etc/nginx/ssl:ro

      # ロギングディレクトリ
      - nginxLogs:/var/log/nginx:rw
      # - ./nginx/logs:/var/log/nginx:rw

    # 自動再起動
    restart: always
    depends_on:
      - frontend
      - app
  # フロントエンドのコンテナ
  frontend:
    # ホスト名設定
    hostname: keytol-ui

    # イメージ
    build:
      context: ./keytol-ui
      dockerfile: Dockerfile
      target: development-dependencies-env

    # ディレクトリ共有
    volumes:
      - ./keytol-ui:/app

    restart: always

  # app コンテナ
  app:
    # ホスト名指定
    hostname: app

    # ビルド対象のdockerfileをしてい
    build:
      context: ./app
      dockerfile: dockerfile
      target: Develop
    
    # コードを共有
    volumes:
      - ./app/src:/app/src
    
    # 仮想端末を有効化
    tty: true

    # 自動起動を有効化
    restart: always
  
  # ログ解析コンテナ
  promtail:
    # イメージを指定
    image: grafana/promtail:2.1.0

    # ホスト名を指定
    hostname: promtail

    # コマンドを実行
    command: -config.file=/mnt/config/promtail.yaml

    # ボリュームで設定ファイルとログを共有
    volumes:
      - nginxLogs:/var/log
      - ./grafana/promtail/promtail.yml:/mnt/config/promtail.yaml:ro

    restart: unless-stopped
  
  # grafana loki を立ち上げる
  loki:
    image: grafana/loki
    hostname: loki
    volumes:
      - ./grafana/loki:/loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      
volumes:
  nginxLogs: